### ISSUE TITLE
Performance tips

### ISSUE THREAD

**Issue by mo8it** [dsmiller95/LindenmayerPlantSimulation#8]
Here, we know how many elements we want to push to `node_amounts` and `node_capacities`, therefore, I would call [reserve](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.reserve) or at least [reserve_exact](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.reserve_exact) on both of them before this loop:

https://github.com/dsmiller95/LindenmayerPlantSimulation/blob/5b419ff540ac9bf03fb5782c5314a5eaa8a04cb5/Extern/Rust/system_runtime/src/diffusion/extract_graph.rs#L154-L161

**Comment by mo8it** [comment]
Can you at least estimate how many elements these vectors will at least have? In that case, I would use `with_capacity` instead of `new`:
https://github.com/dsmiller95/LindenmayerPlantSimulation/blob/5b419ff540ac9bf03fb5782c5314a5eaa8a04cb5/Extern/Rust/system_runtime/src/diffusion/extract_graph.rs#L118-#L121

**Comment by mo8it** [comment]
I would try to rewrite this with an iterator to check for bounds only once and prevent casting in a loop:
https://github.com/dsmiller95/LindenmayerPlantSimulation/blob/5b419ff540ac9bf03fb5782c5314a5eaa8a04cb5/Extern/Rust/system_runtime/src/diffusion/extract_graph.rs#L188-L191

Something like the following:
```rust
let start_ind = modified_node.index_in_temp_amount_list as usize;
let end_ind = start_ind + modified_node.total_resource_types.min(amount_parameters.length as i32) as usize;

for (i, n) in node_amounts[start_ind..end_ind].iter_mut().enumerate() {
    *n += source_symbols.param_for(amount_parameters, i)
}
```

Not tested since I can not get the project compiled :(

Choose better namings ;)

**Comment by dsmiller95** [comment]
Thank you for the tips, I am working on getting benchmarking set up in rust alone then I will try these out.

Unfortunately the project currently has a local build dependency to generate the C# binding files. To load the rust project alone, you could replace the build-dependencies in cargo.toml with this:
```
[build-dependencies]
csbindgen = "1.7.0"
```

and use Extern/Rust/system_runtime as the root rust directory. this won't generate proper C# bindings but should get the rust project building.

**Comment by dsmiller95** [comment]
I got some performance tests set up with realistic use cases, and some of these suggestions helped for sure :) 

this is the pr where I explored changes: https://github.com/dsmiller95/LindenmayerPlantSimulation/pull/9

turned out it ended up being a little faster to precompute the vector's sizes in a tight loop. In the future I can estimate the size of these arrays which would likely be faster
